### ISSUE TITLE
what's transaction detail?

### ISSUE THREAD

**Issue by qq976739120** [iexbase/tron-api-python#23]
i find method of offline_sign(),but i don't know the detail of parameter(transaction),can you help me?
I don't find detail in trx document.In addition,do you know how to mul-sign in trx?It looks like you should be good at eth and ripple,i can mul-sign in eth and ripple.Do they have anything in common?trx can use solidity too.

**Comment by serderovsh** [comment]
offline_sign() - Outdated

-- Current

sign() - offline sign
online_sign() - Not recommended! But in the case of attachment of additional parameters, the signature should be carried out online.

multi-sign - It is not yet implemented

**Comment by serderovsh** [comment]
No, the development of multi signing in TRON is not finished.
