### ISSUE TITLE
Missing functionality for interacting with contracts?

### ISSUE THREAD

**Issue by JamesHutchison** [iexbase/tron-api-python#27]
There seems to be code to deploy a contract but nothing to interact with it. You can get by by passing the "parameter" argument in as a keyword argument when creating a contract,, although there's some massaging that needs to be done to get it in the right format, which I haven't gotten around to implementing yet (or does it already exist somewhere?).

Likewise, there's no function that calls `/wallet/triggersmartcontract` although, one can work around it like so:

```
    return tron.manager.request('/wallet/triggersmartcontract', {
        'contract_address': contract_address,
        'owner_address': host.address.hex,
        'function_selector': function_name,
        'fee_limit': 1000000,
        'call_value': 0,
        'parameter': params
    })
```

There's appears to exist a `ContractFunction` class that comes back if you do `contract.all_functions()`, but it's not clear to me how its intended to be used. I can see in tron web that the parameters are encoded using `parameters = abiCoder.encode(types, values).replace(/^(0x)/, '')` but I'm not seeing any similar functionality here.

**Comment by serderovsh** [comment]
triggersmartcontract - Today will be added

**Comment by serderovsh** [comment]
Added.
This is a beta version, soon "triggersmartcontract" will change a lot
