### ISSUE TITLE
Problem when send token

### ISSUE THREAD

**Issue by TronInvestGroup** [iexbase/tron-api-python#28]
When I create a transaction to send a token, I get an error.

**python3.6 test_new_api_tx.py**
Traceback (most recent call last):
  File "test_new_api_tx.py", line 14, in <module>
    send = tron.trx.send_token('TMESRzqhmeDeEGfNU636BKHsEUJCxW9mpJ',1,'TronLottery')
  File "/usr/local/lib/python3.6/dist-packages/tronapi/trx.py", line 369, in send_token
    account
  File "/usr/local/lib/python3.6/dist-packages/tronapi/transactionbuilder.py", line 73, in send_token
    raise InvalidTronError('Invalid amount provided')
tronapi.exceptions.InvalidTronError: Invalid amount provided

But TRC10 tokens use type integer. Therefore, if you correct a couple of lines of code in the kernel, the transaction is created successfully. Please correct the new release. Thank you!

**tronapi/transactionbuilder.py:**

        def send_token(self, to, amount, token_id, account):
        """Transfer Token

        Args:
            to (str): is the recipient address
            amount (float): is the amount of token to transfer
            token_id (str): Token Name(NOT SYMBOL)
            account: (str): is the address of the withdrawal account

        Returns:
            Token transfer Transaction raw data

        """
        if not self.tron.isAddress(to):
            raise InvalidTronError('Invalid recipient address provided')

        #if not isinstance(amount, float) or amount <= 0:
        if not is_integer(amount) or amount <= 0: <<<<<<<<<<<<<<<<<<<<<NEW
            raise InvalidTronError('Invalid amount provided')

        if not is_string(token_id) or not len(token_id):
            raise InvalidTronError('Invalid token ID provided')

        if not self.tron.isAddress(account):
            raise InvalidTronError('Invalid origin address provided')

        _to = self.tron.address.to_hex(to)
        _from = self.tron.address.to_hex(account)
        _token_id = self.tron.toHex(text=token_id)

        if _to == _from:
            raise TronError('Cannot transfer TRX to the same account')

        return self.tron.manager.request('/wallet/transferasset', {
            'to_address': _to,
            'owner_address': _from,
            'asset_name': _token_id,
            #'amount': self.tron.toSun(amount)
            'amount': amount    <<<<<<<<<<<<<<<<<<<<<NEW
})

**Comment by serderovsh** [comment]
Thanks
