### ISSUE TITLE
Receiving KeyError: 'raw_data' 

### ISSUE THREAD

**Issue by ShilazTech** [iexbase/tron-api-python#30]
I wished to send a bet transaction to tronbot.  I used below code for that
`fee_limit =1000000000
multplier =1000000000
bet_value=10*multplier
direction=0 
rollvalue=50
parameters=[{"value":rollvalue,"type":"uint256"},{"value":direction,"type":"uint256"}]
tx=tron.transaction_builder.trigger_smart_contract('TEEXEWrkMFKapSMJ6mErg39ELFKDqEs6w3','GoodLuck',fee_limit,bet_value,parameters,'TQR27jXR4dHdDtjE63MnnUQvecK97rop2y')
`

It produced below tx
{'result': {'result': True}, 'txid': '5deb501b657bc386aa2f015d175c2d1258aacf9f9c6a3bc3b57456e9d423ccb5', 'transaction': {'txID': '47a1328cb6f34b213f5abb9306fc67eeba7cd72feed24890d2372dd2fe370d9d', 'raw_data': {'contract': [{'parameter': {'value': {'data': '16bd160c00000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000000', 'owner_address': '419a536539b2bbdbadb5d2d45afcc1979065b4370c', 'contract_address': '412ec5f63da00583085d4c2c5e8ec3c8d17bde5e28', 'call_value': 10000000000}, 'type_url': 'type.googleapis.com/protocol.TriggerSmartContract'}, 'type': 'TriggerSmartContract'}], 'ref_block_bytes': '6014', 'ref_block_hash': '968c383e5d721d14', 'expiration': 1546249266000, 'fee_limit': 1000000000, 'timestamp': 1546249209653}}}

but when used "tx=tron.trx.sign(tx,True)" command to sign it then it gives above error.

Please see what is the issue or suggest how can i solve it. Thanks a lot

full error is given below

owner_address = transaction['raw_data']['contract'][0]['parameter']['value']['owner_address']

KeyError: 'raw_data'

**Comment by ShilazTech** [comment]
Below is the example of trx and corresponding trigger on blockchain
Trigger
{'txID': 'b67edbecbf9b30d23a996de27f96d17666630ab05a6ab4e481afd28e89a5e2ea', 'raw_data': {'contract': [{'parameter': {'value': {'data': '16bd160c00000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000000', 'owner_address': '419e737d5db19beafc2a9a813211cc73add2d3a872', 'contract_address': '412ec5f63da00583085d4c2c5e8ec3c8d17bde5e28', 'call_value': 10000000}, 'type_url': 'type.googleapis.com/protocol.TriggerSmartContract'}, 'type': 'TriggerSmartContract'}], 'ref_block_bytes': '6d8b', 'ref_block_hash': 'c690ee1a383bb659', 'expiration': 1546259700000, 'fee_limit': 30000, 'timestamp': 1546259643719}, 'signature': ['6c0df20cc3868a182831fbd2b1a79e6a9ef3e7b45d59e7c78cd3cb7f0a4f9364569267cdadb90bb9a87c9ae17bca9eb210057bfcd1b0417873ed69577982b8ef1c']}

Blockchain link for trigger
https://tronscan.org/#/transaction/b67edbecbf9b30d23a996de27f96d17666630ab05a6ab4e481afd28e89a5e2ea

but there is corresponding event on tronbet smart contract

what could be wrong?

**Comment by ShilazTech** [comment]
correction
but there is no corresponding event on tronbet smart contract

what could be wrong?

**Comment by ShilazTech** [comment]
While looking at trx results of my triggers to contract - I see that they are reverted.


{'ret': [{'contractRet': 'REVERT'}], 'signature': ['24cbe88f6aab73fe90763bd32edc5378b5768687db81ecb029605e5e61a8b6e71f5c58d3beab20e06e00f52ddc6979ada4f6e122ef3e84f4c3f6868c3db924781b'], 'txID': '663af13c631e6f28e565401ac1cd9542cf40cd9f017653ded3804fd10e5f068b', 'raw_data': {'contract': [{'parameter': {'value': {'data': '16bd160c00000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000000', 'owner_address': '419e737d5db19beafc2a9a813211cc73add2d3a872', 'contract_address': '412ec5f63da00583085d4c2c5e8ec3c8d17bde5e28', 'call_value': 10000000}, 'type_url': 'type.googleapis.com/protocol.TriggerSmartContract'}, 'type': 'TriggerSmartContract'}], 'ref_block_bytes': 'c0e7', 'ref_block_hash': 'cf65aa69976bbfc3', 'expiration': 1546324080000, 'fee_limit': 600000, 'timestamp': 1546324024120}}
what might be causing it and how to solve it
any help or hint is much appreciated

**Comment by serderovsh** [comment]
Sorry for the long answer, New Year :)
Check problem fixed

**Comment by ShilazTech** [comment]
Thank you. The later issue is not resolved. I have submitted another ticket for that. Please have a look

**Comment by GalymzhanAbdimanap** [comment]
hi, did you solve the problem? I have exactly the same problem, there are no errors, but by contract I see that the transaction failed. thanks

**Comment by GalymzhanAbdimanap** [comment]
The problem was in function_selector. It is necessary that there is no space.

```
returnContent = tron.transaction_builder.trigger_smart_contract(contract_address = smart_contract_address,
                               function_selector = 'returnContentsAuctions(uint256,uint256[])', #!without spaces
                               fee_limit=1000000000,
                               call_value=0,
                               parameters=[ {'type': 'int256', 'value': i}],
                               issuer_address=default_address
                               )
```
