### ISSUE TITLE
SIGERROR

### ISSUE THREAD

**Issue by sonicskye** [iexbase/tron-api-python#32]
Signing a raw transaction using `tron.trx.sign()` on version 3.0.5 (previously `tron.trx.offline_sign()` on version 3.0.2) returns `SIGERROR`
`{'code': 'SIGERROR', 'message': 'validate signature error'}`

**Comment by serderovsh** [comment]
send sample code

**Comment by serderovsh** [comment]
If you add an additional message to the transaction, in this case there will be a problem

**Comment by sonicskye** [comment]
> If you add an additional message to the transaction, in this case there will be a problem.
> If you plan to add comments to the transaction: "Use online_sign()"

Yes, I add a message to the transaction and would really prefer to use `sign` instead of `online_sign`.

   ```
    tr = tron    
    tr.private_key = privKeySender
    tr.default_address = sender
    tx = tr.transaction_builder.send_token(toAddress, amount, tokenID, sender)
    if message:
        tx['raw_data']['data'] = tr.toHex(text=message)
    sign2 = tr.trx.sign(hextx)
```
I suspect the message is not included when computing txID, that is why the signature is incorrect. I haven't investigated further.

**Comment by serderovsh** [comment]
To do this, use the "Сustom API". We do not yet support this feature.
If you want to add comments to the transaction, you need to use "online_sign()"

**Comment by sonicskye** [comment]
Where can I find the Custom API you mentioned?

**Comment by serderovsh** [comment]
https://github.com/tronprotocol/protocol
