### ISSUE TITLE
Missing voting and freezing features?

### ISSUE THREAD

**Issue by NGS99** [iexbase/tron-api-python#34]
Maybe I missed it, but I did not see anything about freezing or voting in the examples or in the docs.  Is this expected to be added soon?

**Comment by serderovsh** [comment]
Vote: https://github.com/iexbase/tron-api-python/blob/master/tronapi/transactionbuilder.py#L273
Freeze: https://github.com/iexbase/tron-api-python/blob/master/tronapi/transactionbuilder.py#L124
Unfreeze: https://github.com/iexbase/tron-api-python/blob/master/tronapi/transactionbuilder.py#L166

**Comment by NGS99** [comment]
Thanks. I was also looking in contracts, but didn't see it there.  Appreciate the info.  Feel free to close.
