### ISSUE TITLE
tronapi  web3 Incompatible

### ISSUE THREAD

**Issue by zhangsj** [iexbase/tron-api-python#35]
# pip3 install web3
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting web3
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/84/7b/8dfe018c0b94a68f88d98ff39c11471ac55ffbcb22cd7ab41010c1476a75/web3-4.8.2-py3-none-any.whl (124kB)
    100% |████████████████████████████████| 133kB 87.2MB/s 
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in /usr/local/lib/python3.7/site-packages (from web3) (0.1.0)
Requirement already satisfied: eth-utils<2.0.0,>=1.2.0 in /usr/local/lib/python3.7/site-packages (from web3) (1.4.1)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in /usr/local/lib/python3.7/site-packages (from web3) (2.21.0)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in /usr/local/lib/python3.7/site-packages (from web3) (1.1.6)
Requirement already satisfied: eth-account<0.4.0,>=0.2.1 in /usr/local/lib/python3.7/site-packages (from web3) (0.3.0)
Collecting eth-abi<2.0.0,>=1.2.0 (from web3)
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/e9/ef/5af786a32ae7ac3aece6489400ea2cee6b2ede7a7b3955e6f55a59442d12/eth_abi-1.3.0-py3-none-any.whl
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in /usr/local/lib/python3.7/site-packages (from web3) (0.2.0)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython" in /usr/local/lib/python3.7/site-packages (from web3) (0.9.0.1)
Requirement already satisfied: websockets<7.0.0,>=6.0.0 in /usr/local/lib/python3.7/site-packages (from web3) (6.0)
Requirement already satisfied: eth-typing<3.0.0,>=1.0.0 in /usr/local/lib/python3.7/site-packages (from eth-utils<2.0.0,>=1.2.0->web3) (2.0.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->web3) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->web3) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->web3) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->web3) (2.8)
Requirement already satisfied: eth-keys<0.3.0,>=0.2.0b3 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.2.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.5.1)
Requirement already satisfied: attrdict<3,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->web3) (2.0.1)
Requirement already satisfied: eth-rlp<1,>=0.1.2 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->web3) (0.1.2)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/site-packages (from eth-abi<2.0.0,>=1.2.0->web3) (0.8.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6; extra == "pycryptodome" in /usr/local/lib/python3.7/site-packages (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.7.3)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.7/site-packages (from cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython"->web3) (0.9.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from attrdict<3,>=2.0.0->eth-account<0.4.0,>=0.2.1->web3) (1.12.0)
Requirement already satisfied: rlp<2,>=0.6.0 in /usr/local/lib/python3.7/site-packages (from eth-rlp<1,>=0.1.2->eth-account<0.4.0,>=0.2.1->web3) (1.1.0)
tronapi 3.1.3 has requirement eth-abi<3.0.0,>=2.0.0b4, but you'll have eth-abi 1.3.0 which is incompatible.
Installing collected packages: eth-abi, web3
  Found existing installation: eth-abi 2.0.0b5
    Uninstalling eth-abi-2.0.0b5:
      Successfully uninstalled eth-abi-2.0.0b5
Successfully installed eth-abi-1.3.0 web3-4.8.2

pip3 install tronapi
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: tronapi in /usr/local/lib/python3.7/site-packages (3.1.3)
Collecting eth-abi<3.0.0,>=2.0.0b4 (from tronapi)
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/63/0d/416f32bf6a4ce2b929c1749f0efaf5b33b6ed80d3928869b48dd458f018e/eth_abi-2.0.0b5-py3-none-any.whl
Requirement already satisfied: eth-account<0.4.0,>=0.2.1 in /usr/local/lib/python3.7/site-packages (from tronapi) (0.3.0)
Requirement already satisfied: eth-utils<2.0.0,>=1.3.0 in /usr/local/lib/python3.7/site-packages (from tronapi) (1.4.1)
Requirement already satisfied: trx-utils in /usr/local/lib/python3.7/site-packages (from tronapi) (1.0.4)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in /usr/local/lib/python3.7/site-packages (from tronapi) (0.1.0)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in /usr/local/lib/python3.7/site-packages (from tronapi) (2.21.0)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.7/site-packages (from tronapi) (3.7.3)
Requirement already satisfied: base58 in /usr/local/lib/python3.7/site-packages (from tronapi) (1.0.3)
Requirement already satisfied: ecdsa in /usr/local/lib/python3.7/site-packages (from tronapi) (0.13)
Requirement already satisfied: attrdict in /usr/local/lib/python3.7/site-packages (from tronapi) (2.0.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in /usr/local/lib/python3.7/site-packages (from tronapi) (0.9.0.1)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from eth-abi<3.0.0,>=2.0.0b4->tronapi) (2.0.0)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/site-packages (from eth-abi<3.0.0,>=2.0.0b4->tronapi) (0.8.1)
Requirement already satisfied: eth-keys<0.3.0,>=0.2.0b3 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->tronapi) (0.2.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->tronapi) (0.5.1)
Requirement already satisfied: eth-rlp<1,>=0.1.2 in /usr/local/lib/python3.7/site-packages (from eth-account<0.4.0,>=0.2.1->tronapi) (0.1.2)
Requirement already satisfied: eth-hash<1.0.0,>=0.1.0 in /usr/local/lib/python3.7/site-packages (from eth-utils<2.0.0,>=1.3.0->tronapi) (0.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->tronapi) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->tronapi) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->tronapi) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests<3.0.0,>=2.16.0->tronapi) (3.0.4)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from attrdict->tronapi) (1.12.0)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.7/site-packages (from cytoolz<1.0.0,>=0.9.0->tronapi) (0.9.0)
Requirement already satisfied: rlp<2,>=0.6.0 in /usr/local/lib/python3.7/site-packages (from eth-rlp<1,>=0.1.2->eth-account<0.4.0,>=0.2.1->tronapi) (1.1.0)
web3 4.8.2 has requirement eth-abi<2.0.0,>=1.2.0, but you'll have eth-abi 2.0.0b5 which is incompatible.
Installing collected packages: eth-abi
  Found existing installation: eth-abi 1.3.0
    Uninstalling eth-abi-1.3.0:
      Successfully uninstalled eth-abi-1.3.0
Successfully installed eth-abi-2.0.0b5

File "checkblock.py", line 14, in <module>
    from web3 import Web3
  File "/usr/local/lib/python3.7/site-packages/web3/__init__.py", line 8, in <module>
    from web3.main import Web3  # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/web3/main.py", line 16, in <module>
    from web3.eth import Eth
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 13, in <module>
    from web3.contract import (
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 33, in <module>
    from web3.utils.abi import (
  File "/usr/local/lib/python3.7/site-packages/web3/utils/abi.py", line 10, in <module>
    from eth_abi.abi import (
ImportError: cannot import name 'collapse_type' from 'eth_abi.abi' (/usr/local/lib/python3.7/site-packages/eth_abi/abi.py)

attrdict==2.0.1
base58==1.0.3
bitcoin==1.1.39
blockcypher==1.0.73
certifi==2018.11.29
chardet==3.0.4
cytoolz==0.9.0.1
ecdsa==0.13
eth-abi==2.0.0b5
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.4.1
hexbytes==0.1.0
idna==2.8
lru-dict==1.1.6
parsimonious==0.8.1
pycryptodome==3.7.3
python-dateutil==2.2
requests==2.21.0
rlp==1.1.0
six==1.12.0
toolz==0.9.0
tronapi==3.1.3
trx-utils==1.0.4
urllib3==1.24.1
web3==4.8.2
websockets==6.0

**Comment by serderovsh** [comment]
we will check everything now

**Comment by jualy007** [comment]
I have meet same problem,  and is there any special reason that need using eth-abi beta version?

**Comment by serderovsh** [comment]
The problem is resolved

**Comment by sitecreate** [comment]
Tell me you wrote that the problem was fixed, but dependencies still have the version "eth-abi> = 2.0.0b6, <3.0.0"

**Comment by serderovsh** [comment]
We tested several times, no conflicts were noticed. (tron-api and web3)

**Comment by sitecreate** [comment]
The latest stable version web3 has a dependency of eth_abi ==1.3. and does not work with beta versions eth_abi. Please help it is very important, work stops

**Comment by serderovsh** [comment]
https://github.com/ethereum/web3.py/blob/master/setup.py#L70

**Comment by sitecreate** [comment]
well have to use the beta version
