### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Gameus** [iexbase/tron-api-python#37]
# pip3 install tronapi
Collecting tronapi
  Using cached https://files.pythonhosted.org/packages/32/c4/82fed9d23d9087b41ece9788b47a53fbe8be93af1464291ee302fde536b0/tronapi-3.1.3.tar.gz
  Ignoring toolz: markers 'implementation_name == "pypy"' don't match your environment
Collecting cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython" (from tronapi)
  Using cached https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz
Collecting eth-abi<3.0.0,>=2.0.0b4 (from tronapi)
  Using cached https://files.pythonhosted.org/packages/d1/a1/61039ba8de300a053bd72c891c67dbcc5253c288c98dd204dea3e2cccb36/eth_abi-2.0.0b7-py3-none-any.whl
Collecting eth-account<0.4.0,>=0.2.1 (from tronapi)
  Using cached https://files.pythonhosted.org/packages/a3/d8/6118bc0e00d6ec092bb02b012989d1018893755eb84da53266412ac359e3/eth_account-0.3.0-py3-none-any.whl

**Collecting eth-utils<2.0.0,>=1.3.0 (from tronapi)
  Could not find a version that satisfies the requirement eth-utils<2.0.0,>=1.3.0 (from tronapi) (from versions: 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0, 0.8.1, 1.0.0b1, 1.0.0b2, 1.0.1, 1.0.2, 1.0.3, 1.1.1, 1.1.2, 1.2.0, 1.2.1)
No matching distribution found for eth-utils<2.0.0,>=1.3.0 (from tronapi)**

**Comment by serderovsh** [comment]
There are no problems with the installation of the module.
Check version "3.6.5 >"

**Comment by Gameus** [comment]
Sorry it's Python 3.5
3.7 - Ok
Thanks

**Comment by serderovsh** [comment]
3.6.5 also supports
**>= 3.6.5**
