### ISSUE TITLE
Bug in tronapi.trx.Trx.verify_message/sign.

### ISSUE THREAD

**Issue by Anon731** [iexbase/tron-api-python#49]
<details>
<summary>Code example</summary>

```python
TRON_SETTINGS = {
    'full_node': 'https://api.shasta.trongrid.io',
    'solidity_node': 'https://api.shasta.trongrid.io',
    'event_server': 'https://api.shasta.trongrid.io',
}

tron = tronapi.Tron(**TRON_SETTINGS)

account = tron.create_account  # XXX: create_account is property.
tron.private_key = account.private_key
tron.default_address = account.address.base58

message = tron.toHex(text='hello')
signed = tron.trx.sign(message)

tron.trx.verify_message(message, signed)

```

</details>

Result is always `ValueError: Signature does not match`.

I've inspected `tronapi.trx.Trx.sign` and `tronapi.trx.Trx.verify_message` and found that they have different code for header definition:

<details>
<summary>tronapi.trx.Trx.sign</summary>

```python
            # Determine which header to attach to the message
            # before encrypting or decrypting
            header = TRX_MESSAGE_HEADER if use_tron else ETH_MESSAGE_HEADER
            header += str(len(transaction))

            message_hash = self.tron.keccak(text=header+transaction)
```

</details>

<details>
<summary>tronapi.trx.Trx.verify_message</summary>

```python
        # Determine which header to attach to the message
        # before encrypting or decrypting
        header = TRX_MESSAGE_HEADER if use_tron else ETH_MESSAGE_HEADER

        message_hash = self.tron.keccak(text=header+message)
```

</details>

Adding `header += str(len(message))` string into `tronapi.trx.Trx.verify_message` fixes the problem.

**Comment by serderovsh** [comment]
https://github.com/iexbase/tron-api-python/commit/f001328244f99730772010216b5d2d3d844fffa1

**Comment by Anon731** [comment]
@serderovsh add new tag please, i can't install version with changes.

**Comment by birdonwheels5** [comment]
@Anon731 Can you please provide a complete working code sample with the added header? I'm trying to use your suggestion but not having much luck.
