### ISSUE TITLE
Mac, pip install tronapi, ImportError: No module named eth_account

### ISSUE THREAD

**Issue by tigermumu** [iexbase/tron-api-python#58]
After installed tronapi by `sudo pip install tronapi`, and run `python account.py` in examples documents, showing error: 
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from tronapi import Tron
  File "/Volumes/D/coins/tron/tron-robot/tronapi/__init__.py", line 11, in <module>
    from eth_account import Account  # noqa: E402
ImportError: No module named eth_account
```
I checked installation logs, shows
`Requirement already satisfied: eth-account<0.4.0,>=0.2.1 in /usr/local/lib/python3.7/site-packages (from tronapi) (0.3.0)`
What should I do ? 
Thank you

**Comment by serderovsh** [comment]
https://travis-ci.com/iexbase/tron-api-python/jobs/242314621

We checked there are no errors.
Everything is installed

**Comment by tigermumu** [comment]
Ok, I checked again
