### ISSUE TITLE
How do I send TRC-10 tokens using this module ?

### ISSUE THREAD

**Issue by crypto-programmer** [iexbase/tron-api-python#76]
How do I send TRC-10 tokens using this module ?

**Comment by serderovsh** [comment]
there is no such function

**Comment by crypto-programmer** [comment]
There is !  
tron = Tron(full_node=full_node,
                    solidity_node=solidity_node,
                    event_server=event_server)
        tron.private_key = SENDER_PRIVATE_KEY
        tron.default_address = SENDER_PUBLIC_KEY
tron.trx.send_token(RECIEVER_PUBLIC_KEY, buy_amount, "token id",
                                SENDER_PUBLIC_KEY) 

Thanks for making this library  :) . I wil certainly donate if I make something .
